# Build upon labwc
## SOURCE_TAG arg must be a version built for the specific image: eg, 39, 40, gts, latest
ARG SOURCE_TAG="latest"
FROM ghcr.io/ialexandermoon/labwc:${SOURCE_TAG}

## NOTES:
# - /var/lib/alternatives is required to prevent failure with some RPM installs
# - All RUN commands must end with ostree container commit
#   see: https://coreos.github.io/rpm-ostree/container/#using-ostree-container-commit
# Install packages from fedora repos
# 
RUN mkdir -p /var/lib/alternatives && \
    rpm-ostree install containerd.io && \
    rpm-ostree install docker-ce && \
    rpm-ostree install docker-ce-cli && \
    rpm-ostree install docker-compose-plugin && \
    ostree container commit
		