name: ulabwc 42 dx
on:
  schedule:
    - cron: '25 10 * * *'  # 10:25am UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-version-dx.yml
    secrets: inherit
    with:
      fedora_version: 42