name: ulabwc 42 dxx
on:
  workflow_dispatch:

jobs:
  build-dxx:
    name: build 42 dxx
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-version-dxx.yml
    secrets: inherit
    with:
      fedora_version: 42

