---
name: ulabwc 41 main
on:
  workflow_call:

jobs:
  build:
    name: build version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-version.yml
    secrets: inherit
    with:
      fedora_version: 41