name: ulabwc 42 dxx
on:
  workflow_dispatch:

jobs:
  build-dxx:
    name: build 41 main
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-main.yml
    secrets: inherit
    with:
      fedora_version: 42

  build-dxx:
    needs: build-main
    name: build 41 dx
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-main-dx.yml
    secrets: inherit
    with:
      fedora_version: 42