---
name: ulabwc-main
on:
  workflow_call:
    inputs:
      fedora_version:
        description: "The Fedora release version: 39, 40, 41 etc"
        required: true
        type: string

jobs:
  build:
    name: build version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-version.yml
    secrets: inherit
    with:
      fedora_version: ${{ inputs.fedora_version }}