---
name: ulabwc 41 dx
on:
  workflow_call:

jobs:
  build:
    name: build version dx
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-version-dx.yml
    secrets: inherit
    with:
      fedora_version: 41